#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bash $HOME/.config/polybar/launch.sh &
feh --bg-fill /usr/share/backgrounds/artix.png
bash $HOME/.config/bspwm/pipewire.sh &
xbacklight -set 10

bspc config border_width         2
bspc config window_gap           5
bspc config focus_follows_pointer true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a MEGAsync state=floating
